language: android
sudo: required

before_script:
    - echo "Trying to accept license using sdkmanager"
    - $ANDROID_HOME/tools/bin/sdkmanager --licenses || true

    #- echo y | android update sdk -u -a -t tools
    # why oh why
    - echo y | android update sdk -u -a -t build-tools-26.0.2
    - echo y | android update sdk -u -a -t build-tools-27.0.1
    - echo y | android update sdk -u -a -t android-27

script:
    - ./gradlew build 

android:
    components:
        #- tools
        #- platform-tools

        - build-tools-27.0.1
        - android-27
