language: android

before_script:
    - echo y | android update sdk -u -a -t tools
    - echo y | android update sdk -u -a -t platform-tools
    - echo y | android update sdk -u -a -t android-27
    - echo y | android update sdk -u -a -t build-tools-27.0.1

script:
    - ./gradlew build 

android:
    components:
        - tools
        - build-tools-27.0.1
        - platform-tools

        - android-27
