language: android
sudo: required

before_script:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > 
    "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
#    - echo y | android update sdk -u -a -t tools
#    - echo y | android update sdk -u -a -t platform-tools
#    - echo y | android update sdk -u -a -t build-tools-26.0.2
#    - echo y | android update sdk -u -a -t android-26

script:
    - ./gradlew build 

android:
    components:
        - tools
        - build-tools-27.0.1
        - platform-tools

        - android-27
