language: android

before_script:
    - echo y | android update sdk -u -a -t tools
    - echo y | android update sdk -u -a -t platform-tools
    - echo y | android update sdk -u -a -t build-tools-26.0.2
    - echo y | android update sdk -u -a -t android-26

android:
    components:
        - tools
        - build-tools-26.0.2
        - platform-tools

        - android-26
